name: Set Code Ready For Deployment

on:
  pull_request:
    branches: [gittest2]

jobs:
  rename-path-in-components:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Replace devPath to prodPath in vue components
      run: |
        find ./frontend/src/components -name "*.vue" -exec sed -i "s/this.prodPath/this.devPath/g" {} \;
    
    - name: Run npm build - Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: run npm build and create dist folder
      run: | 
        cd frontend
        echo "in frontend/ for checking 1"
        ls
        npm ci
        npm run build #--if-present
        
    - name: update static and templates
      run: |
        rm -rf static/* 
        rm -rf templates/*
        echo "in frontend/ for checking 2"
        cd frontend/
        ls
        cd ..
        mv frontend/dist/static/* static/
        mv frontend/dist/index.html templates/
        
    - name: Github commit and push
      uses: Smart-Transportation/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: github-actions-test


